### ISSUE TITLE
PowerCuff might be disabling flashlight

### ISSUE THREAD

**Issue by camezcua12** [rpetrich/Powercuff#1]
Hey! Not sure if this is the right way to post some form of a ticket or possible bug with the tweak, but giving my best shot here!

I’m running iOS 13.5 with unc0ver 5.0.1 on an iPhone XR. I’m not entirely sure if PowerCuff is officially compatible with iOS 13, but it surely worked almost flawlessly so far, and the battery life has been great.

The issue I’ve found, and I believe it comes from this tweak, as some other Reddit users who also use this tweak have experienced the same problem, is that my flashlight gets permanently disabled until I reboot all of a sudden.

Flashlight icons on lockscreen and CC are greyed out, and it will only work back again if a fully reboot, and then re-tether unc0ver.

Then the flashlight is working for a while, but at some point when I’m not using the phone, the icon is disabled back again.

Could you give me any input on wether that’s something this tweak might be causing, or a better way for me to provide you with logs that are helpful on the matter?

**Comment by tomaszpoliszuk** [comment]
I suspect this is happening because you are using heavy mode which disables some device features to save battery (such as flashlight).
